-- Admin floor plan: hall dimensions + per-table layout (normalized 0..1 coordinates)

ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS floor_plan_width INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS floor_plan_height INTEGER NOT NULL DEFAULT 700;

ALTER TABLE tables ADD COLUMN IF NOT EXISTS layout_x DOUBLE PRECISION NULL;
ALTER TABLE tables ADD COLUMN IF NOT EXISTS layout_y DOUBLE PRECISION NULL;
ALTER TABLE tables ADD COLUMN IF NOT EXISTS layout_w DOUBLE PRECISION NULL;
ALTER TABLE tables ADD COLUMN IF NOT EXISTS layout_h DOUBLE PRECISION NULL;
ALTER TABLE tables ADD COLUMN IF NOT EXISTS layout_rotation DOUBLE PRECISION NULL;
