ALTER TABLE tables
ADD COLUMN IF NOT EXISTS can_unite BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE tables
ADD COLUMN IF NOT EXISTS unite_with_table_id INTEGER REFERENCES tables(id) ON DELETE SET NULL;
